application: lesson1
version: 1
runtime: python
api_version: 1

handlers:
- url: /f
  static_dir: f

- url: /a.*
  script: lessona.py

- url: /b.*
  script: lessonb.py

- url: /c.*
  script: lessonc.py

- url: /.*
  script: lesson.py
